[package]
name = "mmdbc"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
arrow = "6.2.0"
arrow-flight = "6.2.0"
tonic = "0.5.2"
tokio = "1.14.0"
rustyline = "9.0.0"
dirs = "4.0.0"
