[package]
name = "mmdbc"
version = "0.1.0"
license = "Apache-2.0"
edition = "2018"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
arrow = "5.5.0"
arrow-flight = "5.5.0"
tonic = "0.5.2"
tokio = "1.12.0"
rustyline = "9.0.0"
dirs = "4.0"
