[package]
name = "mmdb"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
arrow = "9.0.2"
arrow-flight = "9.0.2"
tonic = "0.6.2"
tokio = "1.17.0"
rustyline = "9.1.2"
dirs = "4.0.0"
