[package]
name = "mmdb"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
arrow = "13.0.0"
arrow-flight = "13.0.0"
tonic = "0.7.2"
tokio = "1.18.2"
rustyline = "9.1.2"
dirs = "4.0.0"
