[package]
name = "mmdb"
version = "0.1.0"
edition = "2018"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
datafusion = { git = "https://github.com/apache/arrow-datafusion/", rev = "18dbbb4" }

tokio = "1.9.0"
async-trait = "0.1.50"
futures = "0.3.16"