[package]
name = "mmdbd"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
datafusion = "7.0.0"

tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
async-trait = "0.1.52"
futures = "0.3.21"

arrow-flight = "9.0.2"
tonic = "0.6.2"

snmalloc-rs = "0.2.28"
