[package]
name = "mmdbd"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
datafusion = "6.0.0"

tokio = { version = "1.14.0", features = ["rt-multi-thread"] }
async-trait = "0.1.51"
futures = "0.3.17"

arrow-flight = "6.2.0"
tonic = "0.5.2"

snmalloc-rs = "0.2.28"
