[package]
name = "mmdbd"
version = "0.1.0"
edition = "2018"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
datafusion = { git = "https://github.com/apache/arrow-datafusion/", rev = "18dbbb4" }
num_cpus = "1.13.0"

tokio = "1.9.0"
async-trait = "0.1.50"
futures = "0.3.16"

arrow-flight = "5.0.0"
tonic = "0.4.3"