[package]
name = "mmdbd"
version = "0.1.0"
license = "Apache-2.0"
edition = "2018"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
datafusion = "5.0.0"
num_cpus = "1.13.0"

tokio = "1.10.0"
async-trait = "0.1.51"
futures = "0.3.16"

arrow-flight = "5.1.0"
tonic = "0.5.2"
