[package]
name = "mmdbd"
version = "0.1.0"
license = "Apache-2.0"
edition = "2018"
authors = ["Soeren Kejser Jensen <devel@kejserjensen.dk>"]

[dependencies]
datafusion = "5.0.0"
num_cpus = "1.13.0"

tokio = { version = "1.12.0", features = ["rt-multi-thread"] }
async-trait = "0.1.51"
futures = "0.3.17"

arrow-flight = "5.5.0"
tonic = "0.5.2"

snmalloc-rs = "0.2.28"
